name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Dev Flavor Pipeline
  dev_ci:
    if: github.ref == 'refs/heads/dev' || github.base_ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Firebase Configuration
        run: test -f lib/firebase_options.dart

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze

      - name: Run unit and widget tests with coverage
        run: flutter test --coverage

      - name: Build Dev Debug APK
        run: flutter build apk --debug -t lib/main_dev.dart

      - name: Upload Dev APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  # Prod Flavor Pipeline
  prod_ci:
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Firebase Configuration
        run: test -f lib/firebase_options.dart

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze

      - name: Run unit and widget tests with coverage
        run: flutter test --coverage

      - name: Build Prod Release APK
        run: flutter build apk --release -t lib/main_prod.dart

      - name: Upload Prod APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
